# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.DateField(),
        ),
    ]
